### ISSUE TITLE
Checkout fails

### ISSUE THREAD

**Issue by dmke** [spree-contrib/spree_print_invoice#111]
When going through the checkout process, a user (logged in or not, doesn't matter) gets an `ArgumentError` in `Spree::CheckoutController#update`:

```
ArgumentError (wrong number of arguments (given 3, expected 1)):
  $RBENV_ROOT/versions/2.3.1/lib/ruby/2.3.0/forwardable.rb:133:in `instance_delegate'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/content_item.rb:12:in `block in <class:ContentItem>'
  activesupport (4.2.7.1) lib/active_support/core_ext/object/with_options.rb:67:in `instance_eval'
  activesupport (4.2.7.1) lib/active_support/core_ext/object/with_options.rb:67:in `with_options'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/content_item.rb:11:in `<class:ContentItem>'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/content_item.rb:3:in `<module:Stock>'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/content_item.rb:2:in `<module:Spree>'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/content_item.rb:1:in `<top (required)>'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb ...
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/package.rb:14:in `add'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/package.rb:18:in `block in add_multiple'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/package.rb:18:in `each'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/package.rb:18:in `add_multiple'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/packer.rb:29:in `block in default_package'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/packer.rb:22:in `each'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/packer.rb:22:in `default_package'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/packer.rb:16:in `packages'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/coordinator.rb:25:in `block in build_packages'
  activerecord (4.2.7.1) lib/active_record/relation/delegation.rb:46:in `each'
  activerecord (4.2.7.1) lib/active_record/relation/delegation.rb:46:in `each'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/coordinator.rb:24:in `build_packages'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/coordinator.rb:18:in `packages'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/stock/coordinator.rb:12:in `shipments'
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_core-3.1.1/app/models/spree/order.rb:492:in `create_proposed_shipments'
  state_machines (0.4.0) lib/state_machines/...
  $RBENV_ROOT/versions/2.3.1/gemsets/shop/gems/spree_frontend-3.1.1/app/controllers/spree/checkout_controller.rb:31:in `update'
  [...]
```

This [Gist](https://gist.github.com/dmke/e4706227b0c3c19d5c1fa73d487a4fdd) contains the full error log, `Gemfile` and `Gemfile.lock`. I'm using Ruby 2.3.1, Rails 4.2.7.1, Spree 3.1.1 and `spree_print_invoice` on master branch.

If I remove this gem (and undo the migrations), the user can step through the checkout process without an error.

What happened here and how can I fix this?

**Comment by quocble** [comment]
I have the same issue.

**Comment by basti** [comment]
@dmke @quocble I think we've run into same problem. Did you manage to fix it somehow? Any help would be appreciated.

**Comment by dmke** [comment]
No, sadly not.

This and other problems (with the system as a whole) were too much of a blocker. I since have moved to another system, which fits my needs better.

I'll leave this ticket open until there is some kind of official response (or better yet: fix).

**Comment by nmccafferty** [comment]
Getting the same simply by extending the InvoiceView class in my project:

module Spree
  Printables::Order::InvoiceView.class_eval do
  end
end

Tracked it down to the Printables::Invoice::BaseView & class Printables::BaseView files which have include Forwardable at the top of each file. This is adding the ruby delegate method as an instance method on Object. This is not available on Object by default and is getting invoked instead of the class method available from active support.

Found the following monkey patch works until a fix in this repo can be made:

class Object
  def delegate(*methods)
    Object.delegate(*methods)
  end
end
