### ISSUE TITLE
Break "create order" functionality in admin panel. Spree 3.0

### ISSUE THREAD

**Issue by romul** [spree-contrib/spree_print_invoice#71]
Just try to open `/admin/orders/new`:
```
ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
  friendly_id (5.1.0) lib/friendly_id/finder_methods.rb:23:in `find'
  /Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree-6d8721e0e19d/backend/app/controllers/spree/admin/orders_controller.rb:134:in `load_order'
  /Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree_print_invoice-2b95eec699f8/app/controllers/spree/admin/orders_controller_decorator.rb:7:in `show'
```

**Comment by peterberkenbosch** [comment]
Yes, just had the same issue. Somehow the pdf link rendering for the order page calls the load_order. I think a @order.new_record? condition is needed.

**Comment by romul** [comment]
That's very strange issue... Why and where `new` action calls `show` action?

**Comment by romul** [comment]
Gotcha! Routes overriding in the extension treats `/admin/orders/new` as `/admin/orders/:id`

**Comment by futhr** [comment]
:+1:
